language: scala
sudo: false
scala:
  - "2.11.11"
  - "2.10.6"
jdk:
  - openjdk7
  - oraclejdk8
script:
  - sbt ++${TRAVIS_SCALA_VERSION} test:compile checkScalariform
  - sbt ++${TRAVIS_SCALA_VERSION} test
matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
  - scala: 2.13.0-M1
    jdk: oraclejdk8
  - scala: 2.12.2
    jdk: oraclejdk9
