language: scala
sudo: false
scala:
  - "2.13.4"
  - "2.12.12"
  - "2.11.12"
  - "2.10.7"
jdk:
  - openjdk8
script:
  - sbt ++${TRAVIS_SCALA_VERSION} test:compile checkScalariform
  - sbt ++${TRAVIS_SCALA_VERSION} test
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
  - scala: 3
    jdk: openjdk8
    script:
    - sbt "++ 3.0.0-M2!" test
